import type {
  AdminDataState,
  AdminNotification,
  DashboardStats,
  RecentOrder,
  SalesDataPoint,
} from "./types";

export const dashboardStats: DashboardStats = {
  todaysRevenue: 0,
  revenueChange: 0,
  ordersToday: 0,
  ordersChange: 0,
  completedOrders: 0,
  pendingOrders: 0,
};

export const monthlySales: SalesDataPoint[] = [
  { label: "Jan", amount: 7200 },
  { label: "Feb", amount: 7800 },
  { label: "Mar", amount: 2800 },
  { label: "Apr", amount: 900 },
  { label: "May", amount: 3200 },
  { label: "Jun", amount: 4100 },
  { label: "Jul", amount: 4200 },
  { label: "Aug", amount: 3600 },
  { label: "Sep", amount: 5200 },
  { label: "Oct", amount: 3100 },
  { label: "Nov", amount: 4300 },
  { label: "Dec", amount: 6100 },
];

export const weeklySales: SalesDataPoint[] = [
  { label: "Mon", amount: 1850 },
  { label: "Tue", amount: 1420 },
  { label: "Wed", amount: 1680 },
  { label: "Thu", amount: 2100 },
  { label: "Fri", amount: 2450 },
  { label: "Sat", amount: 2780 },
  { label: "Sun", amount: 2320 },
];

export const notifications: AdminNotification[] = [
  {
    id: "1",
    type: "low_stock",
    title: "Low stock: Matcha Milktea powder",
    timestamp: "10 mins ago",
  },
  {
    id: "2",
    type: "new_order",
    title: "New order received: ORD-1234",
    timestamp: "25 mins ago",
  },
  {
    id: "3",
    type: "low_stock",
    title: "Low stock: Spam",
    timestamp: "1 hour ago",
  },
];

export const recentOrders: RecentOrder[] = [];

const active = { archived: false as const };

export const initialAdminData: AdminDataState = {
  menuCategories: [
    { id: "mc-1", name: "Coffee", description: "Hot and iced coffee drinks", ...active },
    { id: "mc-2", name: "Milktea", description: "Signature milktea and boba", ...active },
    { id: "mc-3", name: "Meals", description: "Rice bowls and comfort food", ...active },
    { id: "mc-4", name: "Snacks", description: "Light bites and pastries", ...active },
  ],
  menuItems: [
    {
      id: "mi-1",
      name: "House Latte",
      description: "Silky espresso with steamed milk",
      price: 145,
      categoryId: "mc-1",
      available: true,
      ...active,
    },
    {
      id: "mi-2",
      name: "Cordova Cold Brew",
      description: "Slow-steeped and smooth",
      price: 135,
      categoryId: "mc-1",
      available: true,
      ...active,
    },
    {
      id: "mi-3",
      name: "Matcha Milktea",
      description: "Creamy earthy matcha milktea",
      price: 129,
      categoryId: "mc-2",
      available: true,
      ...active,
    },
    {
      id: "mi-4",
      name: "Brown Sugar Boba",
      description: "Warm brown sugar pearls with milk",
      price: 139,
      categoryId: "mc-2",
      available: true,
      ...active,
    },
    {
      id: "mi-5",
      name: "Spam Rice Bowl",
      description: "Savory comfort food classic",
      price: 165,
      categoryId: "mc-3",
      available: true,
      ...active,
    },
    {
      id: "mi-6",
      name: "Garlic Fries",
      description: "Crispy fries with roasted garlic",
      price: 99,
      categoryId: "mc-4",
      available: false,
      ...active,
    },
  ],
  stockCategories: [
    { id: "sc-1", name: "Frozen" },
    { id: "sc-2", name: "Grains" },
    { id: "sc-3", name: "Meat" },
    { id: "sc-4", name: "Coffee" },
    { id: "sc-5", name: "Dairy" },
    { id: "sc-6", name: "Milktea" },
  ],
  stockItems: [
    {
      id: "st-1",
      name: "Matcha Milktea powder",
      categoryId: "sc-6",
      quantity: 3,
      unit: "kg",
      lowStockThreshold: 5,
    },
    {
      id: "st-2",
      name: "Spam",
      categoryId: "sc-3",
      quantity: 8,
      unit: "cans",
      lowStockThreshold: 10,
    },
    {
      id: "st-3",
      name: "Arabica Coffee Beans",
      categoryId: "sc-4",
      quantity: 12,
      unit: "kg",
      lowStockThreshold: 5,
    },
    {
      id: "st-4",
      name: "Whole Milk",
      categoryId: "sc-5",
      quantity: 20,
      unit: "L",
      lowStockThreshold: 8,
    },
    {
      id: "st-5",
      name: "Jasmine Rice",
      categoryId: "sc-2",
      quantity: 25,
      unit: "kg",
      lowStockThreshold: 10,
    },
    {
      id: "st-6",
      name: "Frozen Fries",
      categoryId: "sc-1",
      quantity: 15,
      unit: "kg",
      lowStockThreshold: 6,
    },
  ],
  staffAccounts: [
    {
      id: "sf-1",
      name: "Marvin Barro",
      username: "admin",
      email: "owner@eatnrepeat.com",
      password: "admin123",
      role: "admin",
      status: "active",
      ...active,
    },
    {
      id: "sf-2",
      name: "Maria Santos",
      username: "maria",
      email: "maria@eatnrepeat.com",
      password: "staff123",
      role: "staff",
      status: "active",
      ...active,
    },
    {
      id: "sf-3",
      name: "Carlo Reyes",
      username: "carlo",
      email: "carlo@eatnrepeat.com",
      password: "staff123",
      role: "staff",
      status: "active",
      ...active,
    },
    {
      id: "sf-4",
      name: "Jose Mari",
      username: "jose",
      email: "jose@eatnrepeat.com",
      password: "staff123",
      role: "head_staff",
      status: "active",
      ...active,
    },
  ],
  systemSettings: {
    cafeName: "Eat n' Repeat Café",
    branch: "Cordova",
    address: "Cordova, Cebu City",
    phone: "+63 912 345 6789",
    email: "contact@eatnrepeat.com",
    openingTime: "08:00",
    closingTime: "22:00",
    currency: "PHP",
    taxRate: 12,
    lowStockAlerts: true,
    orderNotifications: true,
  },
  deliverySettings: {
    baseDeliveryFee: 49,
    freeDeliveryMinimum: 500,
    maxDeliveryRadiusKm: 5,
  },
  serviceAreas: [
    {
      id: "sa-1",
      name: "Gabi",
      barangay: "Gabi, Cordova",
      deliveryFee: 49,
      active: true,
    },
    {
      id: "sa-2",
      name: "Poblacion",
      barangay: "Poblacion, Cordova",
      deliveryFee: 39,
      active: true,
    },
    {
      id: "sa-3",
      name: "Day-as",
      barangay: "Day-as, Cordova",
      deliveryFee: 59,
      active: true,
    },
    {
      id: "sa-4",
      name: "Buagsong",
      barangay: "Buagsong, Cordova",
      deliveryFee: 69,
      active: false,
    },
  ],
  deliveryOrders: [
    {
      id: "do-1",
      orderNumber: "DEL-1001",
      customerName: "Anna Reyes",
      phone: "+63 917 111 2233",
      address: "Blk 2 Lot 5, Gabi, Cordova",
      serviceAreaId: "sa-1",
      items: "Matcha Milktea x2, Garlic Fries",
      subtotal: 357,
      deliveryFee: 49,
      total: 406,
      status: "out_for_delivery",
      orderedAt: "2026-06-24T10:15:00",
      ...active,
    },
    {
      id: "do-2",
      orderNumber: "DEL-1002",
      customerName: "Jake Mendoza",
      phone: "+63 918 222 3344",
      address: "Poblacion Road, Cordova",
      serviceAreaId: "sa-2",
      items: "Spam Rice Bowl, House Latte",
      subtotal: 310,
      deliveryFee: 39,
      total: 349,
      status: "preparing",
      orderedAt: "2026-06-24T10:42:00",
      ...active,
    },
    {
      id: "do-3",
      orderNumber: "DEL-1003",
      customerName: "Liza Cruz",
      phone: "+63 919 333 4455",
      address: "Day-as Coastal Rd, Cordova",
      serviceAreaId: "sa-3",
      items: "Brown Sugar Boba x3",
      subtotal: 417,
      deliveryFee: 59,
      total: 476,
      status: "confirmed",
      orderedAt: "2026-06-24T11:05:00",
      ...active,
    },
    {
      id: "do-4",
      orderNumber: "DEL-0998",
      customerName: "Mark Villanueva",
      phone: "+63 920 444 5566",
      address: "Gabi Proper, Cordova",
      serviceAreaId: "sa-1",
      items: "Cordova Cold Brew x2",
      subtotal: 270,
      deliveryFee: 49,
      total: 319,
      status: "delivered",
      orderedAt: "2026-06-23T18:20:00",
      deliveredAt: "2026-06-23T19:05:00",
      ...active,
    },
    {
      id: "do-5",
      orderNumber: "DEL-0995",
      customerName: "Paul Tan",
      phone: "+63 921 555 6677",
      address: "Poblacion, Cordova",
      serviceAreaId: "sa-2",
      items: "Grilled Cheese & Soup",
      subtotal: 189,
      deliveryFee: 39,
      total: 228,
      status: "delivered",
      orderedAt: "2026-06-22T12:30:00",
      deliveredAt: "2026-06-22T13:10:00",
      ...active,
    },
    {
      id: "do-6",
      orderNumber: "DEL-0990",
      customerName: "Sofia Lim",
      phone: "+63 922 666 7788",
      address: "Buagsong, Cordova",
      serviceAreaId: "sa-4",
      items: "Cinnamon Roll x2",
      subtotal: 230,
      deliveryFee: 69,
      total: 299,
      status: "cancelled",
      orderedAt: "2026-06-21T09:00:00",
      ...active,
    },
  ],
  storeOrders: [
    {
      id: "so-1",
      orderId: "ORD-1234",
      time: "Jun 24, 10:30 AM",
      items: "House Latte, Garlic Fries",
      total: 244,
      status: "completed",
      ...active,
    },
    {
      id: "so-2",
      orderId: "ORD-1230",
      time: "Jun 23, 6:45 PM",
      items: "Matcha Milktea x2",
      total: 258,
      status: "completed",
      ...active,
    },
    {
      id: "so-3",
      orderId: "ORD-1225",
      time: "Jun 22, 1:15 PM",
      items: "Spam Rice Bowl",
      total: 165,
      status: "cancelled",
      archived: true,
      archivedAt: "2026-06-23T08:00:00",
    },
  ],
  attendanceRecords: [
    {
      id: "att-1",
      staffId: "sf-2",
      staffName: "Maria Santos",
      date: "2026-07-13",
      timeIn: "08:15 AM",
      timeOut: "05:00 PM",
      status: "Present",
      totalHours: 8.75,
    },
    {
      id: "att-2",
      staffId: "sf-3",
      staffName: "Carlo Reyes",
      date: "2026-07-13",
      timeIn: "08:35 AM",
      timeOut: "05:30 PM",
      status: "Late",
      totalHours: 8.92,
    },
    {
      id: "att-3",
      staffId: "sf-4",
      staffName: "Jose Mari",
      date: "2026-07-13",
      timeIn: "07:55 AM",
      timeOut: "04:30 PM",
      status: "Present",
      totalHours: 8.58,
    },
    {
      id: "att-4",
      staffId: "sf-2",
      staffName: "Maria Santos",
      date: "2026-07-14",
      timeIn: "08:05 AM",
      status: "Present",
    },
    {
      id: "att-5",
      staffId: "sf-4",
      staffName: "Jose Mari",
      date: "2026-07-14",
      timeIn: "07:50 AM",
      status: "Present",
    },
    {
      id: "att-6",
      staffId: "sf-3",
      staffName: "Carlo Reyes",
      date: "2026-07-14",
      status: "Excused",
      reason: "Medical checkup appointment approved by Jose Mari",
    },
    {
      id: "att-7",
      staffId: "sf-3",
      staffName: "Carlo Reyes",
      date: "2026-07-12",
      status: "Absent",
    },
  ],
};
